name: ci

on:
  push: { branches: ["main"] }
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Install
        run: uv sync --extra dev
      - name: Lint
        run: uv run ruff check .
      - name: Typecheck
        run: uv run mypy provis_ucg
      - name: Tests
        run: uv run pytest
